import { useEffect, useState } from "react";
import { Form, FormGroup, FormControl, Button } from "react-bootstrap";
import Head from "next/head";
import dynamic from "next/dynamic";
const EditorJs = dynamic(() => import("react-editor-js"), { ssr: false });
import { ToastContainer, toast } from "react-toastify";

let editorInstance;

const Editor = (props) => {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [editorTools, setEditorTools] = useState();

  const onSaveHandler = async (editorInstance) => {
    const date = new Date().toISOString();
    try {
      const blogData = await editorInstance.save();
      if (!title || title === "") {
        toast.error("Title cannot be empty. Please enter title");
      } else if (!blogData.blocks[0]) {
        toast.error("Blog cannot be empty. Please enter some data");
      } else {
        props.onSave(title, description, JSON.stringify(blogData), date);
      }
    } catch (err) {
      console.log(err);
    }
  };

  let editorComponent;
  if (!editorTools) editorComponent = "Loading...";
  else {
    editorComponent = (
      <EditorJs
        instanceRef={(instance) => (editorInstance = instance)}
        tools={editorTools}
        placeholder={`Let's write an awesome blog!`}
      />
    );
  }

  useEffect(() => {
    const importConstants = async () => {
      const tools = (await import("./tools")).default;
      setEditorTools(tools);
    };

    importConstants();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="row mb-2 font-robo">
        <h2 className="col">Create Blog</h2>

        <div className="col text-end">
          <Button
            className="btn btn-primary px-4 rounded-3"
            onClick={() => onSaveHandler(editorInstance)}
          >
            Publish
          </Button>
        </div>
      </div>

      <FormGroup className="mb-3">
        <Form.Label className="fw-bold font-robo">Title</Form.Label>
        <FormControl
          aria-describedby="basic-addon1"
          placeholder="Your Blog Title"
          value={title}
          onChange={(event) => setTitle(event.target.value)}
        />
      </FormGroup>

      <FormGroup className="mb-3">
        <Form.Label className="fw-bold font-robo">Title</Form.Label>
        <FormControl
          as="textarea"
          aria-describedby="basic-addon1"
          placeholder="Your Blog Description"
          value={description}
          onChange={(event) => setDescription(event.target.value)}
        />
      </FormGroup>

      {editorComponent}
      <ToastContainer />
    </div>
  );
};

export default Editor;
